apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-deployment
  namespace: faelamine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mon-app
  template:
    metadata:
      labels:
        app: mon-app
    spec:
      containers:
      - name: mon-app
        image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
  namespace: faelamine
spec:
  selector:
    app: mon-app
  ports:
    - protocol: TCP
      port: 83
      targetPort: 80
  type: LoadBalancer
