apiVersion: apps/v1
kind: Deployment
metadata:
  name: ma-bd-deployment
  namespace: faelamine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: my-db
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: faelamine-db
        - name: MYSQL_USER
          value: fael
        - name: MYSQL_PASSWORD
          value: amine
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: ma-bd-service
  namespace: faelamine
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer

